apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
data:
  EUREKA_ENABLED: "false"
  KAFKA_BOOTSTRAP_SERVERS: "main-cluster-kafka-bootstrap.kafka:9092"
  MONGO_DATABASE: "paymentservice"
  MONGO_USERNAME: "payment-service"
  MONGO_HOST: "payment-service-mongodb-svc:27017"
  KAFKA_AUTO_CREATE_TOPICS: "false"