apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  EUREKA_ENABLED: "false"
  DB_HOST: "user-service-db-rw"
  DB_PORT: "5432"
  DB_NAME: "userservice"
  REDIS_HOST: "user-service-redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://auth-service.auth-service:80"
  APP_LOGGING_LEVEL: "debug"