apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: api-gateway
data:
  EUREKA_ENABLED: "false"
  USER_SERVICE_URL: "http://user-service.user-service:80"
  AUTH_SERVICE_URL: "http://auth-service.auth-service:80"
  ORDER_SERVICE_URL: "http://order-service.order-service:80"
  PAYMENT_SERVICE_URL: "http://payment-service.payment-service:80"
  AUTH_GRPC_ADDR: "dns://auth-service.auth-service:9090"
  USER_GRPC_ADDR: "dns://user-service.user-service:9090"
  APP_LOGGING_LEVEL: "debug"
